spring:
  config:
    import: file:.env[.properties]
  application:
    name: tanahora

server:
  port: ${PORT:8080}

  jackson:
    time-zone: America/Sao_Paulo

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:ta-na-hora}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:FAKE_API_KEY}
      chat:
        options:
          model: ${OPENAI_MODEL:gpt-3.5-turbo}
          max-tokens: ${OPENAI_MAX_TOKENS:1000}


tanahora:
  whatsapp:
    enabled: ${TANAHORA_WHATSAPP_ENABLED:false}
    from-number: ${TANAHORA_WHATSAPP_FROM_NUMBER:"+0000000000"}
    verify-token: ${TANAHORA_WHATSAPP_VERIFY_TOKEN:fAkE_vErIfY_tOkEn}
    access-token: ${TANAHORA_WHATSAPP_ACCESS_TOKEN:FAKE_ACCESS_TOKEN}
  scheduler:
    enabled: ${TANAHORA_SCHEDULER_ENABLED:true}
    fixed-delay-ms: ${TANAHORA_SCHEDULER_FIXED_DELAY_MS:60000}
    send-reminders-delay-ms: ${TANAHORA_SCHEDULER_SEND_REMINDERS_DELAY_MS:300000}

logging:
  level:
    com.abba: debug
