spring:
  config:
    import: file:.env[.properties]
  application:
    name: tictacmed

  jackson:
    time-zone: America/Sao_Paulo

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:tic-tac-med}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:FAKE_API_KEY}
      chat:
        options:
          model: ${OPENAI_MODEL:gpt-3.5-turbo}
          max-tokens: ${OPENAI_MAX_TOKENS:1000}


tictacmed:
  whatsapp:
    enabled: ${TICTACMED_WHATSAPP_ENABLED:false}
    from-number: ${TICTACMED_WHATSAPP_FROM_NUMBER:"+0000000000"}
    template: "Hello {patientName}, it's time to take your {medicineName} at {scheduledAt}."
    verify-token: ${TICTACMED_WHATSAPP_VERIFY_TOKEN:fAkE_vErIfY_tOkEn}
    access-token: ${TICTACMED_WHATSAPP_ACCESS_TOKEN:FAKE_ACCESS_TOKEN}
  scheduler:
    enabled: ${TICTACMED_SCHEDULER_ENABLED:true}
    fixed-delay-ms: ${TICTACMED_SCHEDULER_FIXED_DELAY_MS:60000}
    send-reminders-delay-ms: ${TICTACMED_SCHEDULER_SEND_REMINDERS_DELAY_MS:300000}

logging:
  level:
    com.abba: debug
